import { FC } from "react";

import styles from "./styles.module.scss";

// whole component generated by chat gpt according to his wishes

/* Panel with information about translation */
const TranslationPanel: FC = () => {
    return (
        <div
            role="note"
            className={styles["translation-credit"]}
            aria-label="Translation credit: English version"
        >
            <div
                aria-hidden="true"
                className={styles["tc-badge"]}
            >
                <svg
                    viewBox="0 0 24 24"
                    width="18"
                    height="18"
                    fill="currentColor"
                    focusable="false"
                    aria-hidden="true"
                >
                    <path d="M12 2l1.3 3.8L17 7l-3.7 1.2L12 12l-1.3-3.8L7 7l3.7-1.2L12 2zm6.5 9.5l.8 2.2 2.2.8-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.8.8-2.2zM5.5 11l.7 1.9 1.9.7-1.9.7-.7 1.9-.7-1.9-1.9-.7 1.9-.7.7-1.9z" />
                </svg>
            </div>

            <div
                className={styles["tc-content"]}
            >
                <div
                    className={styles["tc-title"]}
                >
                    English translation
                </div>
                <p
                    className={styles["tc-text"]}
                >
                    This documentation was translated to English with the help of
                    {` `}
                    <strong>
                        ChatGPT (GPT-5 Thinking)
                    </strong>
                    .
                    {` `}
                </p>
            </div>

            <a
                target="_blank"
                rel="noreferrer"
                className={styles["tc-link"]}
                href="https://chat.openai.com"
            >
                Learn more
                <svg
                    viewBox="0 0 24 24"
                    width="16"
                    height="16"
                    fill="currentColor"
                    aria-hidden="true"
                    focusable="false"
                >
                    <path d="M14 3h7v7h-2V6.4l-9.3 9.3-1.4-1.4L17.6 5H14V3z" />
                    <path d="M19 21H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h7v2H5v14h14v-7h2v7a2 2 0 0 1-2 2z" />
                </svg>
            </a>
        </div>
    );
};

export default TranslationPanel;
